swagger: '2.0'
info:
  title: "\u0421\u0438\u0441\u0442\u0435\u043C\u0430 \u043E\u043F\u0440\u043E\u0441\
    \u043E\u0432"
  contact:
    name: Yuri
    email: yurmezence@gmail.com
  license:
    name: YM License
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /available-surveys/:
    get:
      operationId: available-surveys_list
      description: |-
        Активные опросы (Доступные для прохождения на данный момент времени)
        Список всех активных опросов
        Получение опроса по id
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/AvailableSurvey'
      tags:
        - available-surveys
    parameters: []
  /available-surveys/{id}/:
    get:
      operationId: available-surveys_read
      description: |-
        Активные опросы (Доступные для прохождения на данный момент времени)
        Список всех активных опросов
        Получение опроса по id
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AvailableSurvey'
      tags:
        - available-surveys
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this survey.
        required: true
        type: integer
  /survey/:
    get:
      operationId: survey_list
      description: |-
        Опросы
        Получение списка пройденных опросов,
        создание нового опроса,
        просмотр результатов опроса по id,
        просмотр всех опросов пользователя по user_id
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/SurveyList'
      tags:
        - survey
    post:
      operationId: survey_create
      description: |-
        Опросы
        Получение списка пройденных опросов,
        создание нового опроса,
        просмотр результатов опроса по id,
        просмотр всех опросов пользователя по user_id
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Survey'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Survey'
      tags:
        - survey
    parameters: []
  /survey/user/{user_id}/:
    get:
      operationId: survey_get_user_surveys
      description: "\u0421\u043F\u0438\u043E\u043A \u043E\u043F\u0440\u043E\u0441\u043E\
        \u0432 \u043F\u0440\u043E\u0439\u0434\u0435\u043D\u043D\u044B\u0445 \u043F\
        \u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u043C"
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/SurveyList'
      tags:
        - survey
    parameters:
      - name: user_id
        in: path
        required: true
        type: string
  /survey/{id}/:
    get:
      operationId: survey_read
      description: |-
        Опросы
        Получение списка пройденных опросов,
        создание нового опроса,
        просмотр результатов опроса по id,
        просмотр всех опросов пользователя по user_id
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SurveyList'
      tags:
        - survey
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this survey result.
        required: true
        type: integer
definitions:
  Choice:
    required:
      - text
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      text:
        title: "\u0412\u0430\u0440\u0438\u0430\u043D\u0442 \u043E\u0442\u0432\u0435\
          \u0442\u0430"
        type: string
        maxLength: 300
        minLength: 1
  Question:
    required:
      - type
      - order_num
      - text
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      type:
        title: "\u0422\u0438\u043F \u0432\u043E\u043F\u0440\u043E\u0441\u0430"
        type: string
        enum:
          - text
          - choice
          - choice_multiple
      order_num:
        title: "\u041D\u043E\u043C\u0435\u0440 \u0432\u043E\u043F\u0440\u043E\u0441\
          \u0430"
        type: integer
      text:
        title: "\u0422\u0435\u043A\u0441\u0442 \u0432\u043E\u043F\u0440\u043E\u0441\
          \u0430"
        type: string
        maxLength: 300
        minLength: 1
      choices:
        type: array
        items:
          $ref: '#/definitions/Choice'
        readOnly: true
  AvailableSurvey:
    required:
      - name
      - start_at
      - finish_at
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043E\u043F\u0440\
          \u043E\u0441\u0430"
        type: string
        maxLength: 150
        minLength: 1
      start_at:
        title: "\u041D\u0430\u0447\u0430\u043B\u043E \u0434\u0435\u0439\u0441\u0442\
          \u0432\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430"
        type: string
        format: date-time
      finish_at:
        title: "\u041E\u043A\u043E\u043D\u0447\u0430\u043D\u0438\u0435 \u0434\u0435\
          \u0439\u0441\u0442\u0432\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430"
        type: string
        format: date-time
      questions:
        type: array
        items:
          $ref: '#/definitions/Question'
        readOnly: true
  AnswerList:
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      question:
        $ref: '#/definitions/Question'
      choice:
        title: "\u0412\u0430\u0440\u0438\u0430\u043D\u0442 \u043E\u0442\u0432\u0435\
          \u0442\u0430"
        type: integer
        x-nullable: true
      text:
        title: "\u0422\u0435\u043A\u0441\u0442\u043E\u0432\u043E\u0439 \u043E\u0442\
          \u0432\u0435\u0442"
        type: string
        maxLength: 300
        x-nullable: true
  SurveyList:
    required:
      - survey
      - answers
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      survey:
        title: "\u041E\u043F\u0440\u043E\u0441"
        type: integer
      user:
        title: "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\
          \u044C"
        type: integer
        x-nullable: true
      created_at:
        title: "\u041E\u043A\u043E\u043D\u0447\u0430\u043D\u0438\u0435 \u0434\u0435\
          \u0439\u0441\u0442\u0432\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430"
        type: string
        format: date-time
        readOnly: true
      answers:
        type: array
        items:
          $ref: '#/definitions/AnswerList'
  Answer:
    required:
      - question
    type: object
    properties:
      question:
        title: "\u0412\u043E\u043F\u0440\u043E\u0441"
        type: integer
      choice:
        title: "\u0412\u0430\u0440\u0438\u0430\u043D\u0442 \u043E\u0442\u0432\u0435\
          \u0442\u0430"
        type: integer
        x-nullable: true
      text:
        title: "\u0422\u0435\u043A\u0441\u0442\u043E\u0432\u043E\u0439 \u043E\u0442\
          \u0432\u0435\u0442"
        type: string
        maxLength: 300
        x-nullable: true
  Survey:
    required:
      - survey
      - answers
    type: object
    properties:
      survey:
        title: "\u041E\u043F\u0440\u043E\u0441"
        type: integer
      user:
        title: "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\
          \u044C"
        type: integer
        x-nullable: true
      created_at:
        title: "\u041E\u043A\u043E\u043D\u0447\u0430\u043D\u0438\u0435 \u0434\u0435\
          \u0439\u0441\u0442\u0432\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430"
        type: string
        format: date-time
        readOnly: true
      answers:
        type: array
        items:
          $ref: '#/definitions/Answer'
