# Generated by Django 3.1.5 on 2021-01-18 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название опроса')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Начало действия опроса')),
                ('finish_at', models.DateTimeField(db_index=True, verbose_name='Окончание действия опроса')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Окончание действия опроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.survey', verbose_name='Опрос')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('choice', 'Один вариант ответа'), ('choice_multiple', 'Несколько вариантов ответа')], max_length=15, verbose_name='Тип вопроса')),
                ('order_num', models.IntegerField(verbose_name='Номер вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Текстовой ответ')),
                ('choice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_choices', to='survey.choice', verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='survey.question', verbose_name='Вопрос')),
                ('survey_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyresult', verbose_name='Пройденный опрос')),
            ],
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('order_num', 'survey_id'), name='survey_question_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(order_num__gt=0), name='survey_question_order_num__gt_0'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(('choice__isnull', False), ('text__isnull', False), _connector='OR'), name='not_both_answer_options_null'),
        ),
    ]
